spring.application.name=climalert

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=fepampin@frba.utn.edu.ar
spring.mail.password=${CLIMALERT_MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
climalert.notificaciones.receptores=felipampin23@gmail.com
#admin@clima.com,emergencias@clima.com,meteorologia@clima.com

climalert.reglas.max-temperatura=35.0
climalert.reglas.max-humedad=60.0
climalert.ubicacion=CABA

climalert.api.base-url=http://api.weatherapi.com/v1/current.json
climalert.api.key=${CLIMALERT_API_KEY}

climalert.scheduler.fetch-rate=300000
climalert.scheduler.analysis-rate=60000